# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy (as np)

In [1]:
import numpy as np

#### Set the seed to 0

In [2]:
np.random.seed(0)

#### Create an array of 10 zeros 

In [3]:
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [4]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [6]:
fives_array = np.full(10, 5)
print(fives_array)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50 (in order)

In [7]:
integers_array = np.arange(10, 51)
print(integers_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [8]:
evens_array = np.arange(10, 51, 2)
print(evens_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 5x5 matrix with values ranging from 0 to 8

#### Create a 3x3 identity matrix

In [10]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [11]:
random_number = np.random.rand()
print(random_number)

0.5488135039273248


#### Use NumPy to generate a 5x5 matrix of 25 random numbers sampled from a standard normal distribution

In [12]:
random_matrix = np.random.randn(5, 5)
print(random_matrix)

[[ 0.74159174  1.55291372 -2.2683282   1.33354538 -0.84272405]
 [ 1.96992445  1.26611853 -0.50587654  2.54520078  1.08081191]
 [ 0.48431215  0.57914048 -0.18158257  1.41020463 -0.37447169]
 [ 0.27519832 -0.96075461  0.37692697  0.03343893  0.68056724]
 [-1.56349669 -0.56669762 -0.24214951  1.51439128 -0.3330574 ]]


#### Create the following matrix (hint: use `linspace` with `reshape`):

In [31]:
array = np.linspace(0.01, 1.01, 100).reshape(10, 10)
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


Expected result:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

#### Create an array of 20 linearly spaced points between 0 and 1:

In [22]:
array = np.linspace(0, 1, 20)
print(array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [63]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
sub_mat = mat[2:5, 1:]
print (sub_mat)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


```python 
[Output]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [49]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
sub_mat = mat[3:4, 4:5]
print (sub_mat)

[[20]]


```python 
[Output]:
20
```

In [51]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
sub_mat = mat[1:4, 1:2]
print (sub_mat)

[[ 7]
 [12]
 [17]]


```python 
[Output]:
array([[ 2],
       [ 7],
       [12]])

```

In [52]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
sub_mat = mat[4:5, 0:]
print (sub_mat)

[[21 22 23 24 25]]


```python 
[Output]:
array([21, 22, 23, 24, 25])

```

In [53]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
sub_mat = mat[3:5, 0:]
print (sub_mat)

[[16 17 18 19 20]
 [21 22 23 24 25]]


```python 
[Output]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

### Conditional Indexing (AKA fancy indexing)

In [84]:
import numpy as np
np.random.seed(0)

In [85]:
mat = np.random.randint(-5, 50, size=[5,5])
mat

array([[39, 42, 48, -5, -2],
       [-2, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

#### Select all elements that are greater than 5.

In [86]:
sub_mat = mat[mat > 5]
print(sub_mat)

[39 42 48 34 14 16 45 31 18 19 19  7 33 34 18 41 19 12 32]


Expected result:
```python
array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])
```

#### Select all rows where the first element is less than or equal to 20.

In [87]:
selected_rows = mat[mat[:,0] <= 20]
print (selected_rows)

[[-2 34  4 14 16]
 [19  7 -4 33 34]
 [18 41 19 12 32]]


Expected result:
```python
array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Replace all negative elements with 0.

In [88]:
mat[mat < 0] = 0
mat

array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Calculate the sum of all elements that are less than or equal to 5.

In [89]:
sum_mat = np.sum(mat[mat <= 5])
sum_mat

5

Expected result: `5`

### Calculate the mean of all elements in the last column.

In [90]:
mean_last_col = np.mean(mat[:, -1])
mean_last_col

20.2

Expected result: `20.2`

#### Count the number of elements that are not equal to 0.

In [91]:
count_nonzero = np.count_nonzero(mat)
count_nonzero

21

Expected result: `21`

#### Replace all elements equal to the maximum value of the matrix with 0.

In [92]:
max_val = np.max(mat)
mat[mat == max_val] = 0
mat

array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Math on rows and columns

#### Add 5 to a all mat elements

In [93]:
mat = mat + 5
mat

array([[44, 47,  5,  5,  5],
       [ 5, 39,  9, 19, 21],
       [50, 36, 23,  6, 24],
       [24, 12,  5, 38, 39],
       [23, 46, 24, 17, 37]])

#### Get the sum of all the values in mat

In [94]:
sum_mat = np.sum(mat)
sum_mat

603

#### Get the standard deviation of the values in mat

In [95]:
std_mat = np.std(mat)
std_mat

15.007518115931095

#### Get the sum of all the columns in mat

In [96]:
sum_cols = np.sum(mat, axis=0)
sum_cols

array([146, 180,  66,  85, 126])

#### Get the sum of all the rows in mat

In [97]:
sum_rows = np.sum(mat, axis=1)
sum_rows

array([106,  93, 139, 118, 147])

# Great Job!